server:
 port: 8083
#to connect to service registry
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
spring:
  application:
    name: TASK-SERVICE 
  #to get the repo uri from config service
  config:
    import: configserver:http://localhost:8888

